version: '3'

services:
  phpfpm:
    container_name: app_phpfpm
    build:
      context: ./
      dockerfile: zdocker.phpfpm
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
    ports:
      - "80:80" 
  mysql:
    container_name: app_mysql
    image: mysql:5.7
    volumes:
     - ${HOME}/commentsmysql/app:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: app_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - PHP_UPLOAD_MAX_FILESIZE=100MB
      - PMA_HOST=mysql
